import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/ban-ts-comment": "off",
      "@typescript-eslint/no-wrapper-object-types": "off",
      "@typescript-eslint/no-unsafe-function-type": "off",
      "@typescript-eslint/no-empty-object-type": "off",
      "@typescript-eslint/no-require-imports": "off",
      "@typescript-eslint/no-unused-expressions": "off",
      "react/no-unescaped-entities": "off",
      "react/jsx-no-undef": "off",
      "react/jsx-no-comment-textnodes": "off",
      "react/display-name": "off",
      "react-hooks/purity": "off",
      "react-hooks/set-state-in-effect": "off",
      "react-hooks/static-components": "off",
      "react-hooks/rules-of-hooks": "off",
      "react-hooks/immutability": "off",
      "react-hooks/refs": "off",
      "react-hooks/exhaustive-deps": "off",
      "@next/next/no-img-element": "off",
      "@next/next/no-html-link-for-pages": "off",
      "@next/next/no-assign-module-variable": "off",
      "prefer-const": "off",
      "no-unused-vars": "off",
      "no-undef": "off",
      "no-console": "off",
    },
  },
  globalIgnores([
    "**/.venv/**",
    "**/.next/**",
    "**/out/**",
    "**/build/**",
    "**/dist/**",
    "**/node_modules/**",
    "**/certifyd-ops/**",
    "**/antigravitycertifyroi/**",
    "**/certifyd-scraper/**",
    "**/certifyroi-site/**",
    "**/scratch/**",
    "**/migrations/**",
    "**/docs/**",
    "**/server/**",
    "**/scripts/**",
    "**/api/**",
    "**/.git/**",
    "**/.github/**",
    "**/.vscode/**",
    "**/.aider*/**",
    "**/*.json",
    "**/*.md",
    "**/*.csv",
    "**/*.py",
    "**/*.sql",
    "**/*.html",
    "**/*.txt",
    "**/*.log",
    "**/*.config.js",
    "**/*.config.mjs",
    "replace_colors.cjs",
  ]),
]);

export default eslintConfig;
